const { jsPDF } = require('jspdf');
const fs = require('fs');

const doc = new jsPDF();
doc.text("Hello world! This is a valid PDF generated by jsPDF.", 10, 10);
const pdfData = doc.output();
fs.writeFileSync('dummy.pdf', Buffer.from(pdfData, 'binary'));
console.log("dummy.pdf created with jsPDF");
